export const types = {
    LOGIN_EXITOSO: 'LOGIN_EXITOSO',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CERRAR_SESION: 'CERRAR_SESION',
    RESET__ERROR: 'RESET__ERROR',
    SET_START_DATE: 'SET_START_DATE',
    OBTENER_USUARIO: 'OBTENER_USUARIO',
    /*REGISTRAR COLABORADOR*/
    REGISTRO_EXITOSO: 'REGISTRO_EXITOSO',
    REGISTRO_ERROR: 'REGISTRO_ERROR',
    /*LISTAR COLABORADOR*/
    OBTENER_COLABORADORES: 'OBTENER_COLABORADORES',
    OBTENER_ERROR: 'OBTENER_ERROR',
    RESETEAR_ERROR_REGISTRO: 'RESETEAR_ERROR_REGISTRO',
    RESET_LOADING: 'RESET_LOADING',
    COLABORADOR_ACTUAL: 'COLABORADOR_ACTUAL',
    COLABORADOR_ACTUAL_RESET: 'COLABORADOR_ACTUAL_RESET',
    ACTUALIZAR_INPUT: 'ACTUALIZAR_INPUT',
    ACTUALIZAR_COLABORADOR: 'ACTUALIZAR_COLABORADOR',
    /* Eliminar */
    ELIMINAR_COLABORADOR: 'ELIMINAR_COLABORADOR',
    ACTUALIZAR_EXITOSO : 'ACTUALIZAR_EXITOSO',
    /* Rutas */
    RUTA_ACTUAL: 'RUTA_ACTUAL',
    RUTA_RESET: 'RUTA_RESET',
    /* valhall */
    LOGIN_VALHALLA: 'LOGIN_VALHALLA',
    LOGIN_VALHALLA_ERROR: 'LOGIN_VALHALLA_ERROR',
    OBTENER_USUARIO_VALHALLA: 'OBTENER_USUARIO_VALHALLA',

    /* Empresas */
    OBTENER_EMPRESAS: 'OBTENER_EMPRESAS',
    OBTENER_EMPRESA: 'OBTENER_EMPRESA',
    OBTENER_AREAS: 'OBTENER_AREAS',
    OBTENER_SEDES: 'OBTENER_SEDES',
    OBTENER_PERFILES: 'OBTENER_PERFILES',
    RESET_EMPRESA: 'RESET_EMPRESA',
    ELIMINAR_EMPRESA: 'ELIMINAR_EMPRESA',
    /*Filtrar usuarios */
    FILTRAR_PAGE: 'FILTRAR_PAGE',
    FILTRAR_SEARCH: 'FILTRAR_SEARCH',
    FILTRAR_GENERO: 'FILTRAR_GENERO',
    FILTRAR_EDAD: 'FILTRAR_EDAD',
    FILTRAR_AREA: 'FILTRAR_AREA',
    FILTRAR_PERFIL: 'FILTRAR_PERFIL',
    FILTRAR_FECHA: 'FILTRAR_FECHA',
    FILTRAR_RESET: 'FILTRAR_RESET',
    /* Filtrar monitoreo medico */
    FILTRAR_MONITOREO_NOMBRES: 'FILTRAR_MONITOREO_NOMBRES',
    FILTRAR_MONITOREO_DNI: 'FILTRAR_MONITOREO_DNI',
    FILTRAR_MONITOREO_PERFIL: 'FILTRAR_MONITOREO_PERFIL',
    FILTRAR_MONITOREO_ESTADO: 'FILTRAR_MONITOREO_ESTADO',
    FILTRAR_MONITOREO_FECHA: 'FILTRAR_MONITOREO_FECHA',
    FILTRAR_MONITOREO_HOY: 'FILTRAR_MONITOREO_HOY',
    FILTRAR_MONITOREO_RESET: 'FILTRAR_MONITOREO_RESET',
    /* Filtrar salas CO2 */
    FILTRAR_SALAS_CO2_SEARCH: 'FILTRAR_SALAS_CO2_SEARCH',
    FILTAR_SALAS_CO2_ORDER_NUMBER: 'FILTAR_SALAS_CO2_ORDER_NUMBER',
    FILTAR_SALAS_CO2_ORDER_NAME: 'FILTAR_SALAS_CO2_ORDER_NAME',
    FILTRAR_SALAS_CO2_RESET: 'FILTRAR_SALAS_CO2_RESET',
    /*Filtrar Monitoreo Ambiente */
    FILTRAR_CO2_MONITOREO_SEARCH: 'FILTRAR_CO2_MONITOREO_SEARCH',
    FILTRAR_CO2_MONITOREO_ESTADO: 'FILTRAR_CO2_MONITOREO_ESTADO',
    FILTRAR_CO2_MONITOREO_RESET: 'FILTRAR_CO2_MONITOREO_RESET', 
    /* Filtrar fecha Monitoreo */
    FILTRAR_CO2_MONITOREO_FECHA: 'FILTRAR_CO2_MONITOREO_FECHA',
    FILTRAR_CO2_RESET_FECHA: 'FILTRAR_CO2_RESET_FECHA',
    /*Cantidad de datos de Atencion co2 */
    CANTIDAD_CO2_ATENCION_URGENCIAS: 'CANTIDAD_CO2_ATENCION_URGENCIAS',
    /*FiltrarIndicadores */
    FILTRAR_INDICADORES_FECHA: 'FILTRAR_INDICADORES_FECHA',
    FILTRAR_INDICADORES_HORA: 'FILTRAR_INDICADORES_HORA',
    FILTRAR_INDICADORES_ESTADO: 'FILTRAR_INDICADORES_ESTADO',
    FILTRAR_INDICADORES_RESET: 'FILTRAR_INDICADORES_RESET',

}