# Generated by Django 4.0.1 on 2023-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelia',
            name='date_initial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelia',
            name='date_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
