#!/usr/bin/node


const Sequelize = require('sequelize');
const sequelize = new Sequelize('existing_database', 'postgres', '', {
  host: 'localhost',
  dialect: 'postgres'
});

const Postre = sequelize.define('postres', {
  nombre: {
    type: Sequelize.STRING
  },
  calorias: {
    type: Sequelize.INTEGER
  }
});

Postre.sync({force: true})
  .then(() => {
    console.log('La tabla ha sido creada con éxito.');
  })
  .catch((error) => {
    console.error('Error al crear la tabla:', error);
  });

sequelize
  .authenticate()
  .then(() => {
    console.log('Conexión a la base de datos exitosa.');
  })
  .catch(err => {
    console.error('No se pudo conectar a la base de datos:', err);
  })
