# Generated by Django 4.0.1 on 2022-01-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_profile_headquarters_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
