# Generated by Django 4.0.1 on 2022-01-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='dni')),
                ('gender', models.CharField(blank=True, choices=[('HOMBRE', 'hombre'), ('MUJER', 'mujer')], max_length=20, null=True, verbose_name='genero')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='edad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='foto')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='fecha de salida')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.area')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.enterprise', verbose_name='Empresa')),
                ('headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.headquarters', verbose_name='Sede de empresa')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.profile', verbose_name='Perfil del colaborador')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
