# Generated by Django 4.0.1 on 2022-01-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_colaborators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colaborators',
            new_name='Colaborator',
        ),
    ]
