# Generated by Django 4.0.1 on 2022-02-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('enterprise', '0005_rename_colaborators_colaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborator',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.device'),
        ),
    ]
