# Generated by Django 4.0.1 on 2022-11-14 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('enterprise', '0007_colaborator_register_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Colaborator',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
