# Generated by Django 4.0.1 on 2022-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='foto')),
                ('gender', models.CharField(blank=True, choices=[('HOMBRE', 'hombre'), ('MUJER', 'mujer')], max_length=20, null=True, verbose_name='genero')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='cumpleaños')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='celular')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='edad')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitar Usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_enterprise', models.BooleanField(default=False)),
                ('email_enterprise', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo de empresa')),
                ('ruc', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
