# Generated by Django 4.0.1 on 2022-01-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_profile_headquarters_area'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_enterprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_enterprise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ruc',
        ),
        migrations.AddField(
            model_name='user',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de salida'),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='dni'),
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.enterprise', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.headquarters', verbose_name='Sede de empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.profile', verbose_name='Perfil del colaborador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='telefono'),
        ),
    ]
