export const data = [
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    },
    {
        name: "Las Palmeras",
        address: "Avenida la Marina",
        email: "laspalmeras@gmail.com",
        phone: 968974237,
        ruc: 208974237,
        departamento: "1A",
    }
]