# Generated by Django 4.0.1 on 2022-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mac_addrees', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion de dispositivo')),
                ('device_identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Identificador del dispositivo')),
                ('available', models.BooleanField(default=False, verbose_name='disponible?')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
