# Generated by Django 4.0.1 on 2022-11-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('enterprise', '0008_remove_colaborator_area_remove_colaborator_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('CO2', 'CO2'), ('HCHO', 'HCHO'), ('HUMIDITY', 'HUMIDITY'), ('LIGHT', 'LIGHT'), ('PIR', 'PIR'), ('PM2', 'PM2'), ('PRESSURE', 'PRESSURE'), ('TEMPERATURE', 'TEMPERATURE'), ('TVOC', 'TVOC'), ('PM10', 'PM10'), ('OZONE', 'OZONE')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='TypeSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
            },
        ),
        migrations.CreateModel(
            name='TypeSensorIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.indicator')),
                ('type_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.typesensor')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor - Indicador',
                'verbose_name_plural': 'Tipo de Sensores - Indicadores',
            },
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
