# Generated by Django 4.0.1 on 2022-11-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_indicator_typesensor_typesensorindicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesensor',
            name='indicators',
            field=models.ManyToManyField(blank=True, through='devices.TypeSensorIndicator', to='devices.Indicator'),
        ),
    ]
