# Generated by Django 4.0.1 on 2022-03-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_local_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
