# Generated by Django 4.0.1 on 2022-06-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_rename_enterprise_ambient_headquarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ambient',
        ),
        migrations.RemoveField(
            model_name='local',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='local',
            name='ambient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.ambient'),
        ),
    ]
