# Generated by Django 4.0.1 on 2022-06-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_sensorco2_estado_actividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorco2',
            old_name='wind_status',
            new_name='estado_dioxido_carbono',
        ),
    ]
