# Generated by Django 4.0.1 on 2022-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_rename_wind_status_sensorco2_estado_dioxido_carbono'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorco2',
            name='pm10',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sensorco2',
            name='status_pm2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
