# Generated by Django 4.0.1 on 2022-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_sensorco2_pm10_sensorco2_status_pm2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_actividad',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_barometric_presion',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_dioxido_carbono',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_humidity',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_illumination',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_infrared',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_infrared_and_visible',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_ozono',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_pir',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_pm2',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_pressure',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_temperature',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='estado_tvoc',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='status_pm2',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True),
        ),
    ]
