# Generated by Django 4.0.1 on 2022-09-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_alter_sensorco2_estado_actividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorco2',
            old_name='status_pm2',
            new_name='status_pm10',
        ),
    ]
