# Generated by Django 4.0.1 on 2022-09-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0016_rename_status_pm2_sensorco2_status_pm10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='actividad',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='barometric_presion',
            new_name='barometric_pressure',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='dioxido_carbono',
            new_name='carbon_dioxide',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_hcho',
            new_name='status_hcho',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_actividad',
            new_name='status_activity',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_barometric_presion',
            new_name='status_barometric_pressure',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_dioxido_carbono',
            new_name='status_carbon_dioxide',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='ozono',
            new_name='ozone',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_humidity',
            new_name='status_humidity',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_illumination',
            new_name='status_illumination',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_infrared',
            new_name='status_infrared',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_infrared_and_visible',
            new_name='status_infrared_and_visible',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_ozono',
            new_name='status_ozone',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_pir',
            new_name='status_pir',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_pm2',
            new_name='status_pm2',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_pressure',
            new_name='status_pressure',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_temperature',
            new_name='status_temperature',
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='estado_tvoc',
            new_name='status_tvoc',
        ),
        migrations.AlterField(
            model_name='sensorco2',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data', to='sensors.device'),
        ),
    ]
