# Generated by Django 4.0.1 on 2022-09-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_rename_descripcion_device_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorco2',
            name='general_status',
            field=models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('CONTAMINATED', 'CONTAMINATED'), ('DANGEROUS', 'DANGEROUS')], default='EXCELLENT', max_length=12),
        ),
    ]
