# Generated by Django 4.0.1 on 2022-09-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_sensorco2_general_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorco2',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='status_activity',
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='barometric_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='status_barometric_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='infrared',
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='status_infrared',
        ),
        migrations.RemoveField(
          model_name='sensorco2',
          name='illumination'
        ),
        migrations.RenameField(
            model_name='sensorco2',
            old_name='infrared_and_visible',
            new_name='illumination'
        ),
        migrations.RemoveField(
            model_name='sensorco2',
            name='status_infrared_and_visible',
        ),
    ]
