# Generated by Django 4.0.1 on 2022-09-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0020_local_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageRoomIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('carbon_dioxide', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_carbon_dioxide', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('humidity', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_humidity', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('illumination', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_illumination', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('pressure', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_pressure', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_temperature', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('tvoc', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_tvoc', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('hcho', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_hcho', models.CharField(blank=True, max_length=400, null=True)),
                ('ozone', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_ozone', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('pm2', models.FloatField(blank=True, max_length=400, null=True)),
                ('status_pm2', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('pm10', models.CharField(blank=True, max_length=400, null=True)),
                ('status_pm10', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('NORMAL', 'NORMAL'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('general_status', models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('CONTAMINATED', 'CONTAMINATED'), ('DANGEROUS', 'DANGEROUS')], default='EXCELLENT', max_length=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.local')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
