# Generated by Django 4.0.1 on 2022-09-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0021_averageroomindicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='averageroomindicators',
            name='count_data',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='averageroomindicators',
            name='pm10',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='averageroomindicators',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.local'),
        ),
    ]
