# Generated by Django 4.0.1 on 2022-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0022_averageroomindicators_count_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageroomindicators',
            name='count_data',
            field=models.IntegerField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
