# Generated by Django 4.0.1 on 2022-11-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0002_indicator_typesensor_typesensorindicator_and_more'),
        ('sensors', '0023_alter_averageroomindicators_count_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='devices.typesensor'),
        ),
    ]
