# Generated by Django 4.0.1 on 2022-12-12 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0024_device_type_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('CLOSE', 'close'), ('OPEN', 'open')], max_length=5, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.local')),
            ],
            options={
                'verbose_name': 'Socket',
                'verbose_name_plural': 'Sockets',
            },
        ),
        migrations.CreateModel(
            name='SocketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('current', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('kwh', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('CLOSE', 'close'), ('OPEN', 'open')], max_length=5, null=True)),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.socket')),
            ],
            options={
                'verbose_name': 'Datos de Socket',
                'verbose_name_plural': 'Datos de los Sockets',
            },
        ),
    ]
