# Generated by Django 4.0.1 on 2022-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0025_socket_socketdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socketdata',
            old_name='kwh',
            new_name='power_sum',
        ),
        migrations.AddField(
            model_name='socketdata',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
