# Generated by Django 4.0.1 on 2023-01-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0026_rename_kwh_socketdata_power_sum_socketdata_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorco2',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_room', to='sensors.local'),
        ),
    ]
