# Generated by Django 4.0.1 on 2023-01-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_enterprise_date_installation'),
        ('sensors', '0027_sensorco2_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='ambient',
        ),
        migrations.AddField(
            model_name='local',
            name='headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enterprise.headquarters'),
        ),
        migrations.DeleteModel(
            name='Ambient',
        ),
    ]
