# Generated by Django 4.0.1 on 2023-02-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0030_rename_is_activate_local_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='registered_indicators',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
