# Generated by Django 4.0.1 on 2023-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0031_local_registered_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
