CO2 = 'CO2'
HCHO = 'HCHO'
HUMIDITY = 'HUMIDITY'
LIGHT = 'LIGHT'
PIR = 'PIR'
PM2 = 'PM2'
PRESSURE = 'PRESSURE'
TEMPERATURE = 'TEMPERATURE'
TVOC = 'TVOC'
PM10 = 'PM10'
OZONE = 'OZONE'
INDICATOR_LIST = (
    CO2,
    HCHO,
    PM2,
    TVOC,
    PM10,
    OZONE,
)

INDICATORS = (
    (CO2, 'CO2'),
    (HCHO, 'HCHO'),
    (HUMIDITY, 'HUMIDITY'),
    (LIGHT, 'LIGHT'),
    (PIR, 'PIR'),
    (PM2, 'PM2'),
    (PRESSURE, 'PRESSURE'),
    (TEMPERATURE, 'TEMPERATURE'),
    (TVOC, 'TVOC'),
    (PM10, 'PM10'),
    (OZONE, 'OZONE')
)

HIGH = 'HIGH'
NORMAL = 'NORMAL'
LOW = 'LOW'

LEVELS = (
    (HIGH, 'HIGH'),
    (NORMAL, 'NORMAL'),
    (LOW, 'LOW')
)

EXCELLENT = 'EXCELLENT'
CONTAMINATED = 'CONTAMINATED'
DANGEROUS = 'DANGEROUS'

GENERAL_STATUS = (
    (EXCELLENT, 'EXCELLENT'),
    (CONTAMINATED, 'CONTAMINATED'),
    (DANGEROUS, 'DANGEROUS')
)

STATUS_ES = {
    LOW: 'BUENO',
    NORMAL: 'MALO',
    HIGH: 'PELIGROSO'
}

# SOCKET

CLOSE = "CLOSE"
OPEN = "OPEN"
SOCKET_STATE = (
    (CLOSE, "close"),
    (OPEN, "open")
)
