export const dataI = [
    {
     "N_RECIBO": "2022-01",
     "Propietario": "ADMINISTRACION",
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 7,
     "Mes": 1,
     "Año": 2022,
     "N_OPE": 4469,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "DEV. DICIEMBRE",
     "Año": 2021,
     "Importe": 1215
    },
    {
     "N_RECIBO": "2022-02",
     "Propietario": "ADMINISTRACION",
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 7,
     "Mes": 1,
     "Año": 2022,
     "N_OPE": 4471,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "DEV. CANASTA",
     "Año": 2021,
     "Importe": 119.5
    },
    {
     "N_RECIBO": "2022-03",
     "Propietario": "ADMINISTRACION",
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 7,
     "Mes": 1,
     "Año": 2022,
     "N_OPE": 4472,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "DEV. POR CUADRE",
     "Año": 2021,
     "Importe": 8.8
    },
    {
     "N_RECIBO": "2022-04",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 24,
     "Mes": 1,
     "Año": 2022,
     "N_OPE": 4473,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-05",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 10,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4481,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. NOVIEMBRE",
     "Año": 2021,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-05",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 10,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4481,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. DICIEMBRE",
     "Año": 2021,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-05",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 10,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4481,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-06",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 14,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4483,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "CUOTA EXTRA VERANO",
     "Año": 2022,
     "Importe": 1197
    },
    {
     "N_RECIBO": "2022-07",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 14,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4483,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. DICIEMBRE",
     "Año": 2021,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-07",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 14,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4483,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-08",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 14,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4484,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-09",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 18,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4486,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-10",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 28,
     "Mes": 2,
     "Año": 2022,
     "N_OPE": 4491,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-11",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 14,
     "Mes": 3,
     "Año": 2022,
     "N_OPE": 4494,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-12",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 22,
     "Mes": 3,
     "Año": 2022,
     "N_OPE": 4497,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-13",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 15,
     "Mes": 3,
     "Año": 2022,
     "N_OPE": 4495,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "A CUENTA ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-14",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 30,
     "Mes": 3,
     "Año": 2022,
     "N_OPE": 4503,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "A CUENTA ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-15",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 4,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4506,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-15",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 4,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4506,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-15",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 4,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4506,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-15",
     "Propietario": "ROBERTO DE GASPERI",
     "DPTO": 103,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 4,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4506,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-16",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4508,
     "Banco": "BBVA",
     "Lugar_de_pago": "OFINA EL POLO",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-17",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4510,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JUNIO",
     "Año": 2021,
     "Importe": 200
    },
    {
     "N_RECIBO": "2022-17",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4510,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-17",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4510,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-17",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4510,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-17",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4510,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-18",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 28,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4516,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "A CUENTA ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-18",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 28,
     "Mes": 4,
     "Año": 2022,
     "N_OPE": 4516,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "A CUENTA ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 1290
    },
    {
     "N_RECIBO": "2022-19",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 17,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4519,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-19",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 17,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4519,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-19",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 17,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4519,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-19",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 17,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4519,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-20",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 17,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4519,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "AREA ACUATICA",
     "Año": 2022,
     "Importe": 317
    },
    {
     "N_RECIBO": "2022-21",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 18,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4520,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-22",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 21,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4521,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "AREA ACUATICA",
     "Año": 2022,
     "Importe": 317
    },
    {
     "N_RECIBO": "2022-23",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 21,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4521,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MAYO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-24",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 31,
     "Mes": 5,
     "Año": 2022,
     "N_OPE": 4527,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MAYO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-25",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 24,
     "Mes": 6,
     "Año": 2022,
     "N_OPE": 4532,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MAYO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-26",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 30,
     "Mes": 6,
     "Año": 2022,
     "N_OPE": 4538,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JUNIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-27",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 22,
     "Mes": 6,
     "Año": 2022,
     "N_OPE": 4530,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JUNIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-28",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 7,
     "Mes": 7,
     "Año": 2022,
     "N_OPE": 4541,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JULIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-29",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 7,
     "Mes": 7,
     "Año": 2022,
     "N_OPE": 4543,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JUNIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-30",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 19,
     "Mes": 7,
     "Año": 2022,
     "N_OPE": 4545,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MARZO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-30",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 19,
     "Mes": 7,
     "Año": 2022,
     "N_OPE": 4545,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ABRIL",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-31",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 21,
     "Mes": 7,
     "Año": 2022,
     "N_OPE": 4547,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JULIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-32",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 3,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4554,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JULIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-33",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 21,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4556,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. AGOSTO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-34",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 25,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4558,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. AGOSTO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-35",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 31,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4560,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. MAYO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-35",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 31,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4560,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JUNIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-35",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 31,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4560,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. JULIO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-36",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 31,
     "Mes": 8,
     "Año": 2022,
     "N_OPE": 4566,
     "Banco": "BCP",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. AGOSTO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-37",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 24,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4573,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. ENERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-37",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 24,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4573,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. FEBRERO",
     "Año": 2022,
     "Importe": 100
    },
    {
     "N_RECIBO": "2022-37",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 24,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4573,
     "Banco": "BBVA",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "AREA ACUATICA",
     "Año": 2022,
     "Importe": 317
    },
    {
     "N_RECIBO": "2022-38",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4569,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. AGOSTO",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-38",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 13,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4569,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "AREA ACUATICA",
     "Año": 2022,
     "Importe": 317
    },
    {
     "N_RECIBO": "2022-39",
     "Propietario": "ROSANNA TONANI",
     "DPTO": 202,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 21,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4571,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 003",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. SETIEMBRE",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-40",
     "Propietario": "LUIS CARLOS VEGA GANOZA",
     "DPTO": 101,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 28,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4574,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. SETIEMBRE",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-41",
     "Propietario": "CARLO ALBERTO TONANI CAMUSSO",
     "DPTO": 201,
     "Tipo_de_pago": "DEPOSITO",
     "Dia": 30,
     "Mes": 9,
     "Año": 2022,
     "N_OPE": 4580,
     "Banco": "BBVA",
     "Lugar_de_pago": "ABONO INMEDIATO 002",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. SETIEMBRE",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-42",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 10,
     "Mes": 10,
     "Año": 2022,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. SETIEMBRE",
     "Año": 2022,
     "Importe": 1390
    },
    {
     "N_RECIBO": "2022-42",
     "Propietario": "CARMEN DE GASPERI",
     "DPTO": 102,
     "Tipo_de_pago": "TRASFERENCIA",
     "Dia": 10,
     "Mes": 10,
     "Año": 2022,
     "Banco": "BCP",
     "Lugar_de_pago": "TRANSFERENCIA ELECTRONICA",
     "Modalidad": "CANCELACION ",
     "Concepto": "MANT. OCTUBRE",
     "Año": 2022,
     "Importe": 1390
    }
   ]