export const dataE = [
    {
      Nombre: "ANTONIO SOLIER RAMIREZ",
      Concepto: "GRATIFICACION FIESTAS PATRIAS",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 1500,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 1500,
    },
    {
      Nombre: "ANTONIO SOLIER RAMIREZ",
      Concepto: "VIGILANCIA",
      Febrero: 3000,
      Marzo: 1500,
      Abril: 1500,
      Mayo: 1500,
      Junio: 1500,
      Julio: 1500,
      Agosto: 1500,
      Septiembre: 1500,
      Octubre: 1500,
      Noviembre: 1500,
      Diciembre: 1500,
      Total: 13500,
    },
    {
      Nombre: "ANTONIO SOLIER RAMIREZ",
      Concepto: "PAGO C.T.S.",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 749.7,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 749.7,
    },
    {
      Nombre: "ANTONIO SOLIER RAMIREZ",
      Concepto: "VACACIONES",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 1500,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 1500,
    },
    {
      Concepto: "AREA ACUATICA 2022",
      Febrero: 0,
      Marzo: 0,
      Abril: 1581.02,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 1581.02,
    },
    {
      Nombre: "CARLO TONANI CAMUSSO",
      Concepto: "ASESORIA",
      Febrero: 2400,
      Marzo: 1200,
      Abril: 1200,
      Mayo: 1200,
      Junio: 1200,
      Julio: 1200,
      Agosto: 1200,
      Septiembre: 1200,
      Octubre: 1200,
      Noviembre: 1200,
      Diciembre: 1200,
      Total: 10800,
    },
    {
      Nombre: "CARLO TONANI CAMUSSO",
      Concepto: "GRATF.FIEST.PATRIAS",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 1200,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 1200,
    },
    {
      Concepto: "COMPRA DE LIQ.PARA ACERO",
      Febrero: 92,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 92,
    },
    { 
      Concepto: "COMPRA DE MANGUERA",
      Febrero: 60,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 60,
    },
    {
      Concepto: "COMPRA TIERRA PREPARADA",
      Febrero: 0,
      Marzo: 0,
      Abril: 30,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 30,
    },
    {
      Concepto: "COPIAS DE LLAVES X CAMBIO DE CHAPA",
      Febrero: 12.5,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 12.5,
    },
    {
      Concepto: "DIFERENCIAS POR CUADRE",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0.04,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 0.04,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "ADMINISTRACION",
      Febrero: 3100,
      Marzo: 1550,
      Abril: 1550,
      Mayo: 1550,
      Junio: 1550,
      Julio: 1550,
      Agosto: 1550,
      Septiembre: 1550,
      Octubre: 1550,
      Noviembre: 1550,
      Diciembre: 1550,
      Total: 13950,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "ANDINOS ASCENSORES",
      Febrero: 1170,
      Marzo: 585,
      Abril: 585,
      Mayo: 585,
      Junio: 585,
      Julio: 585,
      Agosto: 585,
      Septiembre: 585,
      Octubre: 585,
      Noviembre: 585,
      Diciembre: 585,
      Total: 5265,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "CAJA CHICA",
      Febrero: 200,
      Marzo: 100,
      Abril: 100,
      Mayo: 100,
      Junio: 100,
      Julio: 100,
      Agosto: 100,
      Septiembre: 100,
      Octubre: 100,
      Noviembre: 100,
      Diciembre: 100,
      Total: 900,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "EDELNOR 2 MEDIDORES",
      Febrero: 260,
      Marzo: 592.5,
      Abril: 224.5,
      Mayo: 280,
      Junio: 157.5,
      Julio: 154.5,
      Agosto: 140.5,
      Septiembre: 291,
      Octubre: 291,
      Noviembre: 291,
      Diciembre: 291,
      Total: 2100.5,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "ENSERES DE LIMPIEZA",
      Febrero: 232.7,
      Marzo: 0,
      Abril: 0,
      Mayo: 78,
      Junio: 0,
      Julio: 0,
      Agosto: 80,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 390.7,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "GRATIFICACION FIESTAS PATRIAS",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 1550,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 1550,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "MANTENIMIENTO DE JARDINES",
      Febrero: 200,
      Marzo: 100,
      Abril: 100,
      Mayo: 100,
      Junio: 100,
      Julio: 100,
      Agosto: 100,
      Septiembre: 100,
      Octubre: 100,
      Noviembre: 100,
      Diciembre: 100,
      Total: 900,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "SEDAPAL",
      Febrero: 1110.3,
      Marzo: 334.1,
      Abril: 0,
      Mayo: 295,
      Junio: 297.2,
      Julio: 295.6,
      Agosto: 385.7,
      Septiembre: 320.7,
      Octubre: 320.7,
      Noviembre: 320.7,
      Diciembre: 320.7,
      Total: 3038.6,
    },
    {
      Nombre: "MARIA LUISA RATTO",
      Concepto: "TELEFONICA",
      Febrero: 109.2,
      Marzo: 54.6,
      Abril: 54.6,
      Mayo: 54.6,
      Junio: 54.7,
      Julio: 54.6,
      Agosto: 54.7,
      Septiembre: 54.6,
      Octubre: 54.6,
      Noviembre: 54.6,
      Diciembre: 54.6,
      Total: 491.6,
    },
    {
      Concepto: "REPARACIÓN ESCALERA DE EMBARQUE",
      Febrero: 670,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 670,
    },
    {
      Concepto: "TRAMITES A CAPITANIA POR RECLAMOS (4 visitas)",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 200,
      Octubre: 200,
      Noviembre: 200,
      Diciembre: 200,
      Total: 200,
    },
    {
      Concepto: "COMPRA DE BANDERA - REPUESTO ESCOBA",
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 35,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 35,
    },
    {
      Concepto: "COMISION ITF",
      Enero: 0.1,
      Febrero: 0.75,
      Marzo: 0.35,
      Abril: 0.65,
      Mayo: 0.35,
      Junio: 0.35,
      Julio: 0.6,
      Agosto: 0.7,
      Septiembre: 0.35,
      Octubre: 0.35,
      Noviembre: 0.35,
      Diciembre: 0.35,
      Total: 4.2,
    },
    {
      Concepto: "COMISION MANTENIMIENTO",
      Enero: 8,
      Febrero: 8,
      Marzo: 8,
      Abril: 8,
      Mayo: 8,
      Junio: 8,
      Julio: 8,
      Agosto: 8,
      Septiembre: 8,
      Octubre: 8,
      Noviembre: 8,
      Diciembre: 8,
      Total: 72,
    },
    {
      Concepto: "COMISION REPOSICION TJ.DEBITO",
      Enero: 20,
      Febrero: 0,
      Marzo: 0,
      Abril: 0,
      Mayo: 0,
      Junio: 0,
      Julio: 0,
      Agosto: 0,
      Septiembre: 0,
      Octubre: 0,
      Noviembre: 0,
      Diciembre: 0,
      Total: 20,
    },
    {
      Concepto: "COMISION TRANSFERENCIA BCA. INTERNET",
      Enero: 28.1,
      Febrero: 11.6,
      Marzo: 5.8,
      Abril: 5.8,
      Mayo: 5.8,
      Junio: 5.8,
      Julio: 5.8,
      Agosto: 5.8,
      Septiembre: 5.8,
      Octubre: 5.8,
      Noviembre: 5.8,
      Diciembre: 5.8,
      Total: 52.2,
    },
    {
      Concepto: "TOTAL",
      Enero: 28.1,
      Febrero: 12637.050000000001,
      Marzo: 6030.350000000001,
      Abril: 6939.570000000001,
      Mayo: 6506.450000000001,
      Junio: 5558.59,
      Julio: 9804.1,
      Agosto: 7245.4,
      Septiembre: 5915.450000000001,
      Octubre: 5915.450000000001,
      Noviembre: 5915.45,
      Diciembre: 5915.45,
      Total: 60665.06,
    },
  ];
  