# Generated by Django 4.0.1 on 2022-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_reading_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='value',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
