export const data = [
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    },
    {
        name: "Pentamar",
        address: "Avenida la Marina",
        email: "pentamar@gmail.com",
        phone: 963852741,
        ruc: 963214587,
        departamento: "1A",
    }
]